### PR TITLE
WIP Grade Lateness and Weighted Grade Functions

### PR DESCRIPTION
**Pull request by Lairdd1989**
This will when finished close Issue #11 and add functionality to get a Students overall Grade taking into account a submissions weight.

### CODE REVIEW

**Comment by Lairdd1989** [comment]
@pmdredd Could you look at the Database File and see where the conflict is i presume it is to do with you recent PRs

**Comment by pmdredd** [comment]
I've got a branch (that isn't ready for PR yet) [here](https://github.com/Lairdd1989/Uni3rdAGILEProject/tree/add_grades_table_and_TDD_tests) that has some conflicts with this PR, namely refactoring the Grade calc function and adding the separate Grades table, however it isn't merged into master so I'm not sure what the conflict is. I will have a look.

I had some ideas about how we could do the Grade calculations which you can see the code for in the above branch, I think it's worth discussing it on Wednesday's scrum meeting.

I've also just realised the Grades user story was assigned to you and not me, didn't mean to snipe it, sorry!

**Comment by Lairdd1989** [comment]
No worries I will leave it for now then and talk with you on Wednesday about it

**Comment by Lairdd1989** [comment]
Just a note for myself.

SLQ for getting Date Difference

```SELECT DATEDIFF(day, 'courseworkdate', 'submissiondate') AS DateDiff;```

**Comment by pmdredd** [comment]
I've merged by branch into yours and then fixed any merge conflicts with master, so this branch should be ready for merging into master. As per the discussion earlier today, this branch contains all the work for grades (new table, new 'grades' folder with grade related functions, altering some existing queries to JOIN the grades table instead of using the 'raw' grade value).

**Pull request merged**
